import type { Product } from "@/types";

/**
 * Datos simulados usados hasta que `GET /api/productos` exista en el backend.
 * `fetchProducts` en lib/api.ts es la única función a reemplazar cuando el
 * endpoint real esté listo; el resto de la UI no necesita cambiar.
 */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    nombre: "Audífonos Inalámbricos Pro",
    precio: 289.9,
    precioOriginal: 349.9,
    stock: 24,
    marca: "SoundMax",
    departamento: "Electronica",
    imagen_url:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "audio_headphones",
    rating: 4.6,
    numResenas: 328,
    envioGratis: true,
  },
  {
    id: "2",
    nombre: "Licuadora de Alta Potencia",
    precio: 179.5,
    stock: 12,
    marca: "HogarPlus",
    departamento: "Hogar",
    imagen_url:
      "https://images.unsplash.com/photo-1570222094114-d054a817e56b?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "kitchen_appliance",
    rating: 4.3,
    numResenas: 94,
  },
  {
    id: "3",
    nombre: "Chaqueta Impermeable Urbana",
    precio: 249.0,
    precioOriginal: 329.0,
    stock: 8,
    marca: "UrbanWear",
    departamento: "Moda",
    imagen_url:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "outerwear_jacket",
    rating: 4.8,
    numResenas: 156,
    envioGratis: true,
    esNuevo: true,
  },
  {
    id: "4",
    nombre: "Balón de Fútbol Profesional",
    precio: 89.9,
    stock: 40,
    marca: "ProSport",
    departamento: "Deportes",
    imagen_url:
      "https://images.unsplash.com/photo-1614632537197-38a17061c2bd?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "sports_ball",
    rating: 4.5,
    numResenas: 210,
  },
  {
    id: "5",
    nombre: "Set de Brochas de Maquillaje",
    precio: 69.9,
    precioOriginal: 99.9,
    stock: 60,
    marca: "GlowBeauty",
    departamento: "Belleza",
    imagen_url:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "beauty_tools",
    rating: 4.7,
    numResenas: 412,
    envioGratis: true,
  },
  {
    id: "6",
    nombre: "Smartwatch Deportivo",
    precio: 549.0,
    stock: 15,
    marca: "SoundMax",
    departamento: "Electronica",
    imagen_url:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "wearable_tech",
    rating: 4.4,
    numResenas: 87,
    esNuevo: true,
  },
  {
    id: "7",
    nombre: "Cafetera Automática",
    precio: 289.0,
    precioOriginal: 359.0,
    stock: 18,
    marca: "HogarPlus",
    departamento: "Hogar",
    imagen_url:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "kitchen_appliance",
    rating: 4.2,
    numResenas: 63,
  },
  {
    id: "8",
    nombre: "Tenis Running Ligeros",
    precio: 259.9,
    stock: 30,
    marca: "ProSport",
    departamento: "Deportes",
    imagen_url:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "footwear_sneaker",
    rating: 4.6,
    numResenas: 275,
    envioGratis: true,
  },
  {
    id: "9",
    nombre: "Perfume Eau de Parfum 100ml",
    precio: 199.9,
    precioOriginal: 259.9,
    stock: 22,
    marca: "GlowBeauty",
    departamento: "Belleza",
    imagen_url:
      "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "fragrance",
    rating: 4.9,
    numResenas: 501,
    envioGratis: true,
  },
  {
    id: "10",
    nombre: "Set de Bloques de Construcción",
    precio: 119.9,
    stock: 45,
    marca: "KidsWorld",
    departamento: "Juguetes",
    imagen_url:
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "toy_building_blocks",
    rating: 4.7,
    numResenas: 132,
    esNuevo: true,
  },
  {
    id: "11",
    nombre: "Laptop Ultradelgada 14''",
    precio: 2799.0,
    precioOriginal: 3199.0,
    stock: 9,
    marca: "SoundMax",
    departamento: "Electronica",
    imagen_url:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "laptop_computer",
    rating: 4.5,
    numResenas: 58,
    envioGratis: true,
  },
  {
    id: "12",
    nombre: "Canasta Familiar de Abarrotes",
    precio: 149.9,
    stock: 100,
    marca: "MercaFresh",
    departamento: "Supermercado",
    imagen_url:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=800&auto=format&fit=crop",
    categoria_ia: "grocery_bundle",
    rating: 4.3,
    numResenas: 76,
    envioGratis: true,
  },
];
